### ISSUE TITLE
Misc. Documentation Updates 

### ISSUE THREAD

**Issue by libbyhopfauf** [amiaopensource/ltopers#169]
Here are a couple of items that need to be updated in the documentation. Thanks!

1.) Make the reference to the tape name/number/id/serial consistent across all documentation. 

2.) In the "Writing to LTO" section, the command should be updated (you are not prompted to do anything when just running "writelto"):
writelto -t ${tapeserial} /Volumes/${sourcedirectory}

**Comment by retokromer** [comment]
+1

Once you have updated the «regular» documentation, if you wish, I volunteer for updating the man as well (and the `-h`, supposing they are not included in the «regular» ;-)

**Comment by retokromer** [comment]
@libbyhopfauf Has this been resolved in https://github.com/amiaopensource/ltopers/pull/173?

**Comment by privatezero** [comment]
I think @libbyhopfauf was also referencing the other associated info (such as the man page) so I think this is only partially resolved so far

**Comment by retokromer** [comment]
I haven’t noticed incongruencies in the man page when I updated it… yet I am not English speaker/writer.

**Comment by privatezero** [comment]
Ugh! My apologies - I had forgotten about https://github.com/amiaopensource/ltopers/pull/177 also altering the man page!

In that case - it seems that the only part of this issue is updating the `writelto` instructions in the [README](https://github.com/amiaopensource/ltopers/blob/master/README.md#writing-to-lto).

It wasn't mentioned in the original issue, but the notes about rsync seem out of date as well since `gcp` is now used for the original transfer of files.

**Comment by kieranjol** [comment]
I was going to make a new issue about this but I see that @libbyhopfauf beat me to it. I've only looked over a colleagues shoulder who is using ltopers, but it looked like `-t` is mandatory but it's not reflected in the docs.
So I guess 

> 2.) In the "Writing to LTO" section, the command should be updated (you are not prompted to do anything when just running "writelto"):
writelto -t ${tapeserial} /Volumes/${sourcedirectory}

is still valid?

**Comment by retokromer** [comment]
Has this been resolved in https://github.com/amiaopensource/ltopers/commit/ed8ccabe9e5e09bf578e3cf2f043dc48b84fd4fb?

**Comment by dericed** [comment]
Yes, I think so.
